# Generated by Django 3.2.9 on 2021-12-13 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livedashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reddit',
        ),
        migrations.DeleteModel(
            name='Twitter',
        ),
    ]
