# Generated by Django 3.2.9 on 2021-12-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livedashboard', '0002_auto_20211213_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reddit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subreddit', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('sentiment_result', models.CharField(max_length=500)),
                ('text_link_ratio_flag', models.CharField(max_length=500)),
            ],
        ),
    ]
